FROM python:3.10
WORKDIR /app

RUN apt-get update && apt-get install -y \
    net-tools \
    inetutils-ping \
    inetutils-traceroute \
    nano \
    vim-nox \
    fping \
    && rm -rf /var/lib/apt/lists/* \

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY monitoring.py .

CMD ["python", "-u", "monitoring.py"]
