# Generated by Django 5.0.7 on 2024-07-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_tool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvdata',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='csvdata',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='importtask',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='importtask',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
