# Generated by Django 5.0.7 on 2024-07-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_tool', '0002_rename_created_at_csvdata_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtask',
            name='router_group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='importtask',
            name='ssh_key_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
