# Generated by Django 5.0.7 on 2024-07-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_tool', '0003_importtask_router_group_name_importtask_ssh_key_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtask',
            name='backup_profile_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
