# Generated by Django 5.0.7 on 2024-07-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_tool', '0004_importtask_backup_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtask',
            name='import_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='importtask',
            unique_together={('csv_data', 'import_id')},
        ),
    ]
