# Generated by Django 5.2 on 2025-04-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_tool', '0005_importtask_import_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtask',
            name='router_type',
            field=models.CharField(choices=[('monitoring', 'Monitoring Only'), ('routeros', 'Mikrotik (RouterOS)'), ('routeros-branded', 'Mikrotik (Branded)'), ('openwrt', 'OpenWRT')], max_length=100),
        ),
    ]
