# Generated by Django 5.2.11 on 2026-02-18 22:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('router_manager', '0020_alter_router_router_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('capture_output', models.BooleanField(default=False)),
                ('max_retry', models.IntegerField(default=3)),
                ('retry_interval', models.IntegerField(default=30, help_text='Retry interval in seconds')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommandJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_source_name', models.CharField(blank=True, max_length=150, null=True)),
                ('exec_source', models.CharField(choices=[('schedule', 'Schedule'), ('manual', 'Manual')], default='manual', max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='fleet_commander.command')),
                ('user_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommandSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('repeat_interval', models.IntegerField(default=0, help_text='Repeat interval in minutes')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='fleet_commander.command')),
                ('router', models.ManyToManyField(blank=True, related_name='command_schedules', to='router_manager.router')),
                ('router_group', models.ManyToManyField(blank=True, related_name='command_schedules', to='router_manager.routergroup')),
            ],
        ),
        migrations.CreateModel(
            name='CommandVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_type', models.CharField(choices=[('monitoring', 'Monitoring Only'), ('routeros', 'Mikrotik (RouterOS)'), ('routeros-branded', 'Mikrotik (Branded)'), ('openwrt', 'OpenWRT'), ('ubiquiti-airos', 'Ubiquiti airOS')], max_length=100)),
                ('payload', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='fleet_commander.command')),
            ],
        ),
        migrations.CreateModel(
            name='CommandTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_name', models.CharField(blank=True, max_length=100, null=True)),
                ('router_uuid', models.UUIDField()),
                ('command_payload', models.TextField(blank=True, null=True)),
                ('command_executed', models.TextField(blank=True, null=True)),
                ('command_output', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('error', 'Error'), ('success', 'Success'), ('aborted', 'Aborted')], default='pending', max_length=100)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_retry', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='fleet_commander.commandjob')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='router_manager.router')),
                ('command_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_commander.commandvariant')),
            ],
        ),
        migrations.AddIndex(
            model_name='commandvariant',
            index=models.Index(fields=['router_type', 'enabled'], name='fleet_comma_router__2a9c27_idx'),
        ),
        migrations.AddConstraint(
            model_name='commandvariant',
            constraint=models.UniqueConstraint(fields=('command', 'router_type'), name='uniq_command_variant_per_router_type'),
        ),
        migrations.AddIndex(
            model_name='commandtask',
            index=models.Index(fields=['status', 'next_retry'], name='fleet_comma_status_735f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='commandtask',
            index=models.Index(fields=['router_uuid', 'created'], name='fleet_comma_router__e449fb_idx'),
        ),
        migrations.AddIndex(
            model_name='commandtask',
            index=models.Index(fields=['job', 'status'], name='fleet_comma_job_id_490730_idx'),
        ),
        migrations.AddConstraint(
            model_name='commandtask',
            constraint=models.UniqueConstraint(fields=('job', 'router_uuid'), name='uniq_commandtask_job_router_uuid'),
        ),
    ]
