# Generated by Django 5.2.11 on 2026-02-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_commander', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandjob',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
