# Generated by Django 5.2.11 on 2026-02-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_commander', '0002_commandjob_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandjob',
            name='error_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commandjob',
            name='success_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commandjob',
            name='task_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
