# Generated by Django 5.2.11 on 2026-02-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_commander', '0003_commandjob_error_count_commandjob_success_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandjob',
            name='aborted_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
