# Generated by Django 5.0.3 on 2024-04-04 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebadminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='webadmin_settings', max_length=20, unique=True)),
                ('update_available', models.BooleanField(default=False)),
                ('current_version', models.PositiveIntegerField(default=0)),
                ('latest_version', models.PositiveIntegerField(default=0)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
