# Generated by Django 5.0.3 on 2024-04-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerfleet_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webadminsettings',
            name='cron_last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
