# Generated by Django 5.0.3 on 2024-04-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerfleet_tools', '0002_webadminsettings_cron_last_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='webadminsettings',
            name='monitoring_last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webadminsettings',
            name='router_config_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
