# Generated by Django 5.0.3 on 2024-03-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
