# Generated by Django 5.0.3 on 2024-03-16 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0002_alter_router_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_online', models.BooleanField(default=False)),
                ('last_status_change', models.DateTimeField(blank=True, null=True)),
                ('last_backup', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('router', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='router_manager.router')),
            ],
        ),
    ]
