# Generated by Django 5.0.3 on 2024-03-16 18:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0003_routerstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='RouterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('routers', models.ManyToManyField(to='router_manager.router')),
            ],
        ),
    ]
