# Generated by Django 5.0.3 on 2024-03-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0004_router_internal_notes_alter_router_name_routergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshkey',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
