# Generated by Django 5.0.3 on 2024-03-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0006_routergroup_default_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routergroup',
            name='routers',
            field=models.ManyToManyField(blank=True, to='router_manager.router'),
        ),
    ]
