# Generated by Django 5.0.3 on 2024-03-17 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0007_alter_routergroup_routers'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerstatus',
            name='last_backup_failed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_daily_backup', models.DateTimeField(blank=True, null=True)),
                ('next_weekly_backup', models.DateTimeField(blank=True, null=True)),
                ('next_monthly_backup', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('router', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='router_manager.router')),
            ],
        ),
    ]
