# Generated by Django 5.0.3 on 2024-03-17 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
        ('router_manager', '0008_routerstatus_last_backup_failed_backupschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='backup_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.backupprofile'),
        ),
    ]
