# Generated by Django 5.0.3 on 2024-04-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0010_alter_router_router_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerstatus',
            name='backup_lock',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
