# Generated by Django 5.0.3 on 2024-04-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0011_routerstatus_backup_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='router_type',
            field=models.CharField(choices=[('monitoring', 'Monitoring Only'), ('routeros', 'Mikrotik (RouterOS)')], max_length=100),
        ),
    ]
