# Generated by Django 5.0.3 on 2024-04-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0012_alter_router_router_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
