# Generated by Django 5.0.3 on 2024-04-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0013_alter_router_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='router_type',
            field=models.CharField(choices=[('monitoring', 'Monitoring Only'), ('routeros', 'Mikrotik (RouterOS)'), ('openwrt', 'OpenWRT')], max_length=100),
        ),
    ]
