# Generated by Django 5.0.3 on 2024-04-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0014_alter_router_router_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerstatus',
            name='status_online',
            field=models.BooleanField(default=True),
        ),
    ]
