# Generated by Django 5.2 on 2025-04-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0017_alter_router_router_type_routerinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerinformation',
            name='cpu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
