# Generated by Django 5.2 on 2025-04-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0018_routerinformation_cpu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routerinformation',
            name='host_id',
        ),
    ]
