# Generated by Django 5.2.11 on 2026-02-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0019_remove_routerinformation_host_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='router_type',
            field=models.CharField(choices=[('monitoring', 'Monitoring Only'), ('routeros', 'Mikrotik (RouterOS)'), ('routeros-branded', 'Mikrotik (Branded)'), ('openwrt', 'OpenWRT'), ('ubiquiti-airos', 'Ubiquiti airOS')], max_length=100),
        ),
    ]
