# Generated by Django 5.2.11 on 2026-02-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0020_alter_router_router_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerstatus',
            name='command_lock',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
