# Generated by Django 5.0.4 on 2024-04-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagechannel',
            name='channel_type',
            field=models.CharField(choices=[('callmebot', 'CallMeBot (WhatsApp)'), ('telegram', 'Telegram')], max_length=100),
        ),
    ]
