# Generated by Django 5.0.4 on 2024-04-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_center', '0003_message_error_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='next_retry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
