# Generated by Django 5.2.11 on 2026-02-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_center', '0004_message_next_retry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagechannel',
            name='channel_type',
            field=models.CharField(choices=[('callmebot', 'CallMeBot (WhatsApp)'), ('telegram', 'Telegram'), ('ntfy', 'ntfy.sh (public)')], max_length=100),
        ),
    ]
