# Generated by Django 5.2.11 on 2026-02-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_center', '0006_alter_messagechannel_channel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('status_online', 'Status change: Online'), ('status_offline', 'Status change: Offline'), ('backup_fail', 'Backup failed'), ('task_lock_expired', 'Task Lock Expired')], max_length=32),
        ),
    ]
