FROM nginx:alpine
RUN apk --no-cache add openssl
COPY nginx_entrypoint.sh /nginx_entrypoint.sh
COPY virtualhost.conf /etc/nginx/virtualhost.conf.disabled
COPY virtualhost_noredirect.conf /etc/nginx/virtualhost_noredirect.conf.disabled
RUN chmod +x /nginx_entrypoint.sh
ENTRYPOINT ["/nginx_entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]