# Generated by Django 5.0.3 on 2024-04-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalintegration',
            name='wireguard_webadmin_default_user_level',
            field=models.PositiveIntegerField(choices=[(0, 'Do not create users'), (10, 'Debugging Analyst'), (20, 'View Only User'), (30, 'Peer Manager'), (40, 'Manager'), (50, 'Administrator')], default=0),
        ),
    ]
