# Generated by Django 5.0.3 on 2024-03-16 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('router_manager', '0003_routerstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterDownTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_down_time', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='router_manager.router')),
            ],
        ),
    ]
