# Generated by Django 5.0.3 on 2024-03-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_alter_backupprofile_weekly_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupprofile',
            name='retry_interval',
            field=models.IntegerField(choices=[(1, '1 Minute'), (15, '15 Minutes'), (30, '30 Minutes'), (60, '1 Hour')], default=30),
        ),
    ]
