# Generated by Django 5.0.3 on 2024-04-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0005_rename_daily_retenion_backupprofile_daily_retention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupprofile',
            name='retrieve_interval',
            field=models.IntegerField(choices=[(15, '15 Seconds'), (30, '30 Seconds'), (60, '1 Minute'), (900, '15 Minutes'), (1800, '30 Minutes'), (3600, '1 Hour')], default=60),
        ),
    ]
