# Generated by Django 5.0.3 on 2024-04-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0006_alter_backupprofile_retrieve_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupprofile',
            name='profile_error_information',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
