# Generated by Django 5.1.3 on 2024-11-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0008_alter_backupprofile_backup_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupprofile',
            name='parameter_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backupprofile',
            name='parameter_terse',
            field=models.BooleanField(default=False),
        ),
    ]
