# Generated by Django 5.0.3 on 2024-03-17 21:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('router_manager', '0009_router_backup_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('next_retry', models.DateTimeField(blank=True, null=True)),
                ('schedule_time', models.DateTimeField(blank=True, null=True)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('instant', 'Instant')], max_length=10)),
                ('queue_length', models.IntegerField(default=0)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('backup_text', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='router_manager.router')),
            ],
        ),
    ]
