# Generated by Django 5.0.3 on 2024-03-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerbackup',
            name='backup_binary',
            field=models.FileField(blank=True, null=True, upload_to='backups/'),
        ),
        migrations.AddField(
            model_name='routerbackup',
            name='backup_pending_retrieval',
            field=models.BooleanField(default=False),
        ),
    ]
