# Generated by Django 5.0.3 on 2024-03-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_data', '0002_routerbackup_backup_binary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerbackup',
            name='config_change_detected',
            field=models.BooleanField(default=False),
        ),
    ]
