# Generated by Django 5.0.3 on 2024-03-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_data', '0003_routerbackup_config_change_detected'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerbackup',
            name='backup_text_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
