# Generated by Django 5.0.3 on 2024-04-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_data', '0005_alter_routerbackup_backup_text_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerbackup',
            name='backup_text_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
