# Generated by Django 5.2.11 on 2026-02-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_data', '0006_routerbackup_backup_text_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerbackup',
            name='task_console_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
