# Generated by Django 5.2.11 on 2026-02-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_data', '0007_routerbackup_task_console_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerbackup',
            name='task_console_output',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
