# Generated by Django 5.2.11 on 2026-02-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup_data', '0009_routerbackup_task_lock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routerbackup',
            name='task_lock',
        ),
    ]
