# Generated by Django 5.2.11 on 2026-02-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_data', '0010_remove_routerbackup_task_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerbackup',
            name='task_lock',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
